Repository OZ-Coding-School/oz_03_collabo-002-BE, pull requests merged in 2024-08, with the labels that each got.

#2 유저 API 테스트를 위한 PR 입니다
  .github/workflows/ci.yml
  .github/workflows/docker-ci.yml
  Dockerfile
  customk/config/logger.py
  customk/config/settings.py
  customk/config/urls.py
  customk/mypy.ini
  customk/pytest.ini
  customk/ruff.toml
  customk/scripts/start-dev.sh
  customk/users/migrations/0001_initial.py
  customk/users/migrations/0002_user_created_at_user_updated_at.py
  customk/users/migrations/0004_alter_user_email_alter_user_name.py
  customk/users/models.py
  customk/users/serializers/__init__.py
  customk/users/serializers/user_serializer.py
  customk/users/services/__init__.py
  customk/users/services/token_service.py
  customk/users/tests.py
  customk/users/tests/__init__.py
  customk/users/tests/conftest.py
  customk/users/tests/test_kakao_api.py
  customk/users/tests/test_user_api.py
  customk/users/tests/test_user_model.py
  customk/users/urls.py
  customk/users/views.py
  customk/users/views/__init__.py
  customk/users/views/kakao.py
  customk/users/views/user.py
  dev.env
  docker-compose-dev.yml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#3 Dev -> Main 배포 PR 입니다
  .github/workflows/ci.yml
  .github/workflows/docker-ci.yml
  Dockerfile
  customk/config/logger.py
  customk/config/settings.py
  customk/config/urls.py
  customk/mypy.ini
  customk/pytest.ini
  customk/ruff.toml
  customk/scripts/start-dev.sh
  customk/users/migrations/0001_initial.py
  customk/users/migrations/0002_user_created_at_user_updated_at.py
  customk/users/migrations/0004_alter_user_email_alter_user_name.py
  customk/users/models.py
  customk/users/serializers/__init__.py
  customk/users/serializers/user_serializer.py
  customk/users/services/__init__.py
  customk/users/services/token_service.py
  customk/users/tests.py
  customk/users/tests/__init__.py
  customk/users/tests/conftest.py
  customk/users/tests/test_kakao_api.py
  customk/users/tests/test_user_api.py
  customk/users/tests/test_user_model.py
  customk/users/urls.py
  customk/users/views.py
  customk/users/views/__init__.py
  customk/users/views/kakao.py
  customk/users/views/user.py
  dev.env
  docker-compose-dev.yml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#7 유저 소셜로그인 및 사진 기능 구현
  .gitignore
  customk/classes/tests/conftest.py
  customk/classes/tests/test_class_api.py
  customk/classes/views.py
  customk/common/services/__init__.py
  customk/common/services/ncp_api_conf.py
  customk/config/authentication.py
  customk/config/settings.py
  customk/config/urls.py
  customk/mypy.ini
  customk/users/extend_schemas/__init__.py
  customk/users/extend_schemas/social.py
  customk/users/migrations/0005_merge_20240826_1046.py
  customk/users/migrations/0005_user_profile_image.py
  customk/users/migrations/0005_user_profile_image_alter_user_email_alter_user_name.py
  customk/users/migrations/0006_alter_user_profile_image.py
  customk/users/models.py
  customk/users/serializers/user_serializer.py
  customk/users/services/oauth.py
  customk/users/services/token_service.py
  customk/users/tests/conftest.py
  customk/users/tests/test_kakao_api.py
  customk/users/tests/test_token_api.py
  customk/users/tests/test_user_api.py
  customk/users/tests/testimage.png
  customk/users/urls.py
  customk/users/views/facebook.py
  customk/users/views/google.py
  customk/users/views/kakao.py
  customk/users/views/line.py
  customk/users/views/token.py
  customk/users/views/user.py
  dev.env
Labels: enhancement

#11 nginx 설정 변경
  nginx/nginx.conf.template
Labels: bug

#12 리뷰 기능 수정 및 CSRF 추가
  customk/config/settings.py
  customk/reviews/admin.py
  customk/reviews/migrations/0006_alter_reviewimage_image_url.py
  customk/reviews/models.py
  customk/reviews/serializers.py
  customk/reviews/urls.py
  customk/reviews/views.py
Labels: enhancement

#13 setcookie 설정 변경
  customk/users/services/token_service.py
Labels: documentation

#14 Feature admin -> Dev 관리자 페이지 클래스 사진 추가 기능
  customk/classes/admin.py
  customk/classes/forms.py
  customk/classes/utils.py
  customk/config/urls.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#15 Dev -> Main 배포
  customk/classes/admin.py
  customk/classes/forms.py
  customk/classes/utils.py
  customk/config/urls.py
  customk/users/services/token_service.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#18 [Dev -> Main 배포] 쿠키 설정 및 Gunicorn 설정 변경
  customk/config/settings.py
  customk/scripts/start-deploy.sh
  customk/scripts/start-dev.sh
  customk/users/services/oauth.py
  customk/users/services/token_service.py
  customk/users/views/google.py
  customk/users/views/kakao.py
  customk/users/views/line.py
  customk/users/views/user.py
Labels: enhancement

#19 deploy 스크립트 수정
  customk/scripts/start-deploy.sh
Labels: bug
